services:
  apigateway:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/apigateway:latest
    container_name: apigateway_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.apigateway
      - .env
    ports:
      - 5000:5000
    depends_on:
      otel-collector:
        condition: service_started
      auth:
        condition: service_started
      user:
        condition: service_started
      role:
        condition: service_started
      product:
        condition: service_started
      order:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  auth-db:
    image: postgres:17-alpine
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - app_example_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/auth-service:latest
    container_name: auth_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.auth
      - .env
    ports:
      - 50051:50051
      - 8080:8080
    depends_on:
      auth-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  user-db:
    image: postgres:17-alpine
    container_name: user_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - app_example_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/user-service:latest
    container_name: user_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.user
      - .env
    ports:
      - 50052:50052
      - 8081:8081
    depends_on:
      user-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  role-db:
    image: postgres:17-alpine
    container_name: role_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: role_db
    volumes:
      - postgres_role_data:/var/lib/postgresql/data
    networks:
      - app_example_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  role:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/role-service:latest
    container_name: role_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.role
      - .env
    ports:
      - 50053:50053
      - 8082:8082
    depends_on:
      role-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  product-db:
    image: postgres:17-alpine
    container_name: product_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    volumes:
      - postgres_product_data:/var/lib/postgresql/data
    networks:
      - app_example_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  product:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/product-service:latest
    container_name: product_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.product
      - .env
    ports:
      - 50054:50054
      - 8083:8083
    depends_on:
      product-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  order-db:
    image: postgres:17-alpine
    container_name: order_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - app_example_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  order:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/order-service:latest
    container_name: order_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.order
      - .env
    ports:
      - 50055:50055
      - 8084:8084
    depends_on:
      order-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  

  email:
    image: ghcr.io/mamangrust/microservice_simple_ecommerce/email-service:latest
    container_name: email_simple_ecommerce
    restart: unless-stopped
    env_file:
      - .env.email
      - .env
    depends_on:
      email-db:
        condition: service_healthy
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    networks:
      - app_example_ecommerce

  kafka:
    image: bitnami/kafka:latest
    container_name: my-kafka-ecommerce
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@my-kafka-ecommerce:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://my-kafka-ecommerce:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CLUSTER_ID=kraft-cluster-01
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data_ecommerce_data:/bitnami/kafka
    networks:
      - app_example_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server my-kafka-ecommerce:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.4
    command: ["redis-server", "--requirepass", "dragon_knight"]
    ports:
      - "6379:6379"
    volumes:
      - redis_example_ecommerce-data:/data
    restart: unless-stopped
    networks:
      - app_example_ecommerce

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-ecommerce-tonic
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - app_example_ecommerce

  prometheus:
    image: prom/prometheus
    container_name: prometheus-example_ecommerce-tonic
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - app_example_ecommerce

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-example_ecommerce-tonic
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_example_ecommerce-tonic-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app_example_ecommerce

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-example_ecommerce-tonic
    ports:
      - "16686:16686"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    networks:
      - app_example_ecommerce

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector-tonic
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
      - "8889:8889"
    volumes:
      - ./observability/otel-collector.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    restart: unless-stopped
    networks:
      - app_example_ecommerce

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    networks:
      - app_example_ecommerce

  loki:
    container_name: loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_example_ecommerce_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app_example_ecommerce

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.0
    volumes:
      - ./observability/promtail-config.yaml:/etc/promtail/config.yaml
      - ./logs:/var/log/app
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - app_example_ecommerce

networks:
  app_example_ecommerce:
    driver: bridge

volumes:
  grafana_example_ecommerce-tonic-data:
  postgres_auth_data:
  postgres_user_data:
  postgres_role_data:
  postgres_product_data:
  postgres_order_data:
  postgres_email_data:
  redis_example_ecommerce-data:
  loki_example_ecommerce_data:
  kafka_data_ecommerce_data: