[package]
name = "genproto"
version = "0.1.0"
edition = "2024"
build = "build.rs"


[lib]
name = "genproto"
path = "src/lib.rs"

[dependencies]
prost = "0.14.1"
tonic-prost = "0.14.0"
tonic = { workspace = true}

[build-dependencies]
tonic-prost-build = "0.14.0"
